name: Deploy to Firebase Hosting (Simple) - DISABLED

on:
  workflow_dispatch:
    inputs:
      dummy:
        description: 'This workflow is disabled'
        required: false
        default: 'disabled'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: This workflow is disabled
      run: echo "This workflow is disabled. Use deploy.yml instead."
